name: Auto Reviewer

on:
  pull_request:
    types: [opened, edited]

jobs:
  auto_review:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Get modified line number
        id: modified_line
        run: |
          MODIFIED_LINE=$(git diff --unified=0 ${{ github.event.before }} ${{ github.sha }} | grep '^@@' | sed -E 's/@@.*\+(\S+),.*/\1/')
          echo "::set-output name=line::$MODIFIED_LINE"

      - name: Get last commit author
        id: last_commit_author
        run: |
          MODIFIED_LINE="${{ steps.modified_line.outputs.line }}"
          LAST_COMMIT_AUTHOR=$(curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            "https://api.github.com/repos/${{ github.repository }}/commits?per_page=1" \
            | jq -r ".[] | select(.commit.message | contains(\"+$MODIFIED_LINE\")) | .author.login")
          echo "::set-output name=author::$LAST_COMMIT_AUTHOR"

      - name: Add reviewer
        if: github.event_name == 'pull_request'
        run: |
          AUTHOR="${{ steps.last_commit_author.outputs.author }}"
          PR_NUMBER="${{ github.event.pull_request.number }}"
          curl -X POST -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            -H "Content-Type: application/json" \
            -d "{\"reviewers\": [\"$AUTHOR\"]}" \
            "https://api.github.com/repos/${{ github.repository }}/pulls/$PR_NUMBER/requested_reviewers"
