name: Auto Reviewer

on:
  pull_request:
    types: [opened, edited]

jobs:
  add_reviewer:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Get last commit author
        id: last_commit_author
        run: |
          LAST_COMMIT_AUTHOR="${{ github.event.commits[0].author.name }}"
          echo "LAST_COMMIT_AUTHOR=$LAST_COMMIT_AUTHOR" >> $GITHUB_ENV

      - name: Add reviewer
        if: github.event_name == 'pull_request'
        run: |
          AUTHOR="${{ steps.last_commit_author.outputs.LAST_COMMIT_AUTHOR }}"
          PR_NUMBER="${{ github.event.pull_request.number }}"
          echo "Author to add as reviewer: $AUTHOR"
          curl -X POST -H "Authorization: token ${{ secrets.API_TOKEN }}" \
            -H "Content-Type: application/json" \
            -d "{\"reviewers\": [\"$AUTHOR\"]}" \
            "https://api.github.com/repos/${{ github.repository }}/pulls/$PR_NUMBER/requested_reviewers"
